version: '3'
services:
  eureka-server:
    container_name: eureka-server
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - my-network

  test-service:
    container_name: test-service
    build:
      context: ./test-service
      dockerfile: Dockerfile
    networks:
      - my-network
    depends_on:
      - eureka-server  # Ждем, пока eureka-server запустится
    command: sleep 10 && your_start_command_here  # Задержка 10 секунд перед выполнением команды

  test-service2:
    container_name: test-service2
    build:
      context: ./test-service
      dockerfile: Dockerfile
    networks:
      - my-network
    depends_on:
      - eureka-server  # Ждем, пока eureka-server запустится
    command: sleep 10 && your_start_command_here  # Задержка 10 секунд перед выполнением команды

  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge